services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:4000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/go/src/app
    networks:
      - app-network
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ""
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge